---

- name: Ensure base Jellyfin directory exists
  ansible.builtin.file:
    path: "{{ jellyfin_docker_base_directory }}"
    state: 'directory'
    owner: "{{ jellyfin_docker_user }}"
    group: "{{ jellyfin_docker_user }}"
    mode: '0755'
  tags:
    - jellyfin
    - jellyfin_setup

- name: Ensure Jellyfin compose file is present
  ansible.builtin.template:
    src: 'compose.yml.j2'
    dest: "{{ jellyfin_docker_base_directory }}/compose.yml"
    owner: "{{ jellyfin_docker_user }}"
    group: "{{ jellyfin_docker_user }}"
    mode: '0644'
    backup: true
  register: jellyfin_docker_compose_template_result
  tags:
    - jellyfin
    - jellyfin_config

- name: Ensure Jellyfin compose project is deployed
  community.docker.docker_compose_v2:
    project_src: "{{ jellyfin_docker_base_directory }}"
    state: 'present'
    recreate: "{{ 'always' if (jellyfin_docker_compose_template_result.changed) else 'auto' }}"
    remove_orphans: true
  tags:
    - jellyfin
    - jellyfin_deploy
